<?php

return [
    'admin_password' => env('ATK_ADMIN_PASSWORD', 'admin123'),
    'items' => [
        ['category' => '📄 Kertas', 'name' => 'Kertas A4 (kwarto)'],
        ['category' => '📄 Kertas', 'name' => 'Kertas F4 (folio)'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Ordner warna merah'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Ordner warna kuning'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Ordner warna putih'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Ordner warna biru'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Binder kenko no. 280'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Binder kenko no. 260'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Binder kenko no. 200'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Binder kenko no. 155'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Binder kenko no. 111'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Binder kenko no. 107'],
        ['category' => '📁 Ordner & Binder', 'name' => 'Binder kenko no. 105'],
        ['category' => '🔋 Baterai', 'name' => 'Baterai Alkaline AA'],
        ['category' => '🔋 Baterai', 'name' => 'Baterai Alkaline AAA'],
        ['category' => '🔋 Baterai', 'name' => 'Baterai ABC'],
        ['category' => '🔋 Baterai', 'name' => 'Baterai Energizer Max'],
        ['category' => '🔋 Baterai', 'name' => 'Baterai Energizer Small'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Tinta Brother BT D 60BK'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Tinta Brother BT 5000 Y'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Tinta Brother BT 5000 M'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Tinta Brother BT 5000 C'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Tinta Brother LC 3617 BK'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Tinta Brother LC 3617 C'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Tinta Brother LC 3617 Y'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Tinta Brother LC 3617 M'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Brother LC 462 BK'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Brother LC 462 M'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Brother LC 462 Y'],
        ['category' => '🖨️ Tinta Brother', 'name' => 'Brother LC 462 C'],
        ['category' => '🖨️ Tinta Canon', 'name' => 'Tinta Canon 790 BK'],
        ['category' => '🖨️ Tinta Canon', 'name' => 'Tinta Canon 790 Y'],
        ['category' => '🖨️ Tinta Canon', 'name' => 'Tinta Canon 790 M'],
        ['category' => '🖨️ Tinta Canon', 'name' => 'Tinta Canon 790 C'],
        ['category' => '🖨️ Tinta Canon', 'name' => 'Tinta Canon 746'],
        ['category' => '🖨️ Tinta Canon', 'name' => 'Tinta Canon 745'],
        ['category' => '🖨️ Tinta Canon', 'name' => 'Tinta Canon 811 warna'],
        ['category' => '🖨️ Tinta Canon', 'name' => 'Tinta Canon 810 hitam'],
        ['category' => '🖨️ Tinta Canon', 'name' => 'Tinta Canon 740'],
        ['category' => '🖨️ Tinta Canon', 'name' => 'Tinta Canon 741'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson 664 BK'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson 664 Y'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson 664 M'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson 664 C'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson 003 C'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson 003 BK'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson 003 Y'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson 003 M'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson WF 5390 BK'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson WF 5390 C'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson WF 5390 Y'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Epson WF 5390 M'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Cartridge tambahan WF-5390 BK'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Cartridge tambahan WF-5390 C'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Cartridge tambahan WF-5390 Y'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Cartridge tambahan WF-5390 M'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Injeksi WF-5390 BK'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Injeksi WF-5390 C'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Injeksi WF-5390 Y'],
        ['category' => '🖨️ Tinta Epson', 'name' => 'Tinta Injeksi WF-5390 M'],
        ['category' => '🖨️ Tinta HP & Lainnya', 'name' => 'Tinta HP 680 hitam'],
        ['category' => '🖨️ Tinta HP & Lainnya', 'name' => 'Tinta HP 680 warna'],
        ['category' => '🖨️ Tinta HP & Lainnya', 'name' => 'Tinta 85 A'],
        ['category' => '🖨️ Tinta HP & Lainnya', 'name' => 'Tinta 35 A'],
        ['category' => '🖨️ Tinta HP & Lainnya', 'name' => 'Cartridge Toner'],
        ['category' => '🖨️ Tinta HP & Lainnya', 'name' => 'Stamp Pad 50 cc'],
        ['category' => '🖨️ Tinta HP & Lainnya', 'name' => 'Tinta isi ulang (multi ink)'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Pena Signo hitam'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Pena signo biru'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Pena Bouliner biru'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Pena Bouliner hitam'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Pena Pilot biru'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Pena pilot hitam'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Pena Kenko hitam'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Pena kenko biru'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Pensil HB'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Ball Point Pen'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Twin pen'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Snowman Blue'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Stabilo bos'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Spidol Permanent'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Spidol white board'],
        ['category' => '✏️ Alat Tulis', 'name' => 'Paint Marker Artline 400XF'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Lem Glue stick'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Stick note besar'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Stick note kecil'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Pisau cutter kenko L 500'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Pisau cutter kenko A 300'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Pisau Cutter Kenko L-150'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Paper clip atom'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Stapler besar'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Stapler kecil no. 10'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Isi Stapler no. 10'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Isi stapler besar'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Sign here'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Pita koreksi (tipex kertas)'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Correction Tape'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Rautan (peruncing)'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Penghapus'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Penggaris besi 30 inc'],
        ['category' => '📌 Perlengkapan Kantor', 'name' => 'Gunting stainless sedang'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Flashdis 64 GB'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Flashdis 32 GB'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Flashdis 16 GB'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Flashdis 8 GB'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Isolasi Hitam'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Isolasi kertas'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Isolasi bening'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Isolasi coklat'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Doble tip'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Buku kwitansi'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Tissue Paseo'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Amplop putih polos panjang'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'amplop putih polos pendek'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Buku Expedisi sedang'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Buku expedisi kecil'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'Mouse Logitec M 185'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'USB 2.0 AM/AF'],
        ['category' => '📦 Perlengkapan Lain', 'name' => 'USB Adapter High gain wireless'],
    ],
    'units' => [
        'pcs',
        'pak',
        'box',
        'lusin',
        'rim',
    ],
];
